export type TemplateSwitch =
    | 'newSignUp'
    | 'forgetPassword'
    | 'resetPassword'
    | 'verifyEmail'
    | 'setPassword'
    | 'surveyInvite'
    | 'payoutRequest'
    | 'inviteToProject'
    | 'feedback'
    | 'feedbackReply'
    | 'technologyGlitch'
    | 'userInterview'