version: "3.8"

services:
  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - ${DATABASE_PORT}

volumes:
  node_modules_cache:
  redis-data:
  postgres-data:

networks:
  internal-network:
