export const jwtConstants = {
  secret: process.env.JWT_SECRET || 'secret',
};

export const typesOfLaw = {
  "ADM 03": "Administrative",
  "ADM 14": "Administrative",
  "ADM 18": "Administrative",
  "ADM1": "Administrative",
  "ADM10": "Administrative",
  "ADM11": "Administrative",
  "ADM2": "Administrative",
  "ADM3": "Administrative",
  "ADM4": "Administrative",
  "ADM5": "Administrative",
  "ADM6": "Administrative",
  "ADM7": "Administrative",
  "ADMIN 03": "Administrative",
  "ADMIN 15": "Administrative",
  "ADP 02": "Family",
  "ADP 03": "Family",
  "ADP 12": "Family",
  "ADP12": "Family",
  "ADP8": "Family",
  "APP1": "Appellate",
  "APP10": "Appellate",
  "APP12": "Appellate",
  "APP2": "Appellate",
  "APP6": "Appellate",
  "APPEAL 14": "Appellate",
  "APPEAL01": "Appellate",
  "APPEAL02": "Appellate",
  "APPEAL10": "Appellate",
  "BANK 01": "Miscellaneous",
  "BANK 03": "Miscellaneous",
  "BANK 17": "Miscellaneous",
  "BEV LAW 08": "Civil",
  "BEV LAW 14": "Civil",
  "BEV LAW 18": "Civil",
  "CIV 12": "Civil",
  "CIV 15": "Civil",
  "CIV 17": "Civil",
  "CIV1": "Civil",
  "CIV10": "Civil",
  "CIV18": "Civil",
  "CIV2": "Civil",
  "CIV20": "Civil",
  "CIV21": "Civil",
  "CIV3": "Civil",
  "CIV4": "Civil",
  "CIV5": "Civil",
  "CIV6": "Civil",
  "CIV7": "Civil",
  "CIV8": "Civil",
  "CIVIL LIT 14": "Civil",
  "CIVRGT03": "Civil",
  "COL 10": "Civil",
  "COL2": "Civil",
  "COL3": "Civil",
  "COL4": "Civil",
  "COL5": "Civil",
  "COL6": "Civil",
  "COL7": "Civil",
  "COLL 01": "Civil",
  "COLL 15": "Civil",
  "COLL10": "Civil",
  "COLL14": "Civil",
  "COMM 12": "Civil",
  "COMM 15": "Civil",
  "CONSFR 14": "Civil",
  "CONTRACT 01": "Civil",
  "CONTRACT 12": "Civil",
  "CONTRACT 14": "Civil",
  "CONTRACT 8": "Civil",
  "CORP 08": "Civil",
  "CORP 12": "Civil",
  "CORP 20": "Civil",
  "CORP 3": "Civil",
  "CORP14": "Civil",
  "CORP7": "Civil",
  "CH1": "Criminal",
  "CRIM  15": "Criminal",
  "CRIM 18": "Criminal",
  "CRIM14": "Criminal",
  "CRM 17": "Criminal",
  "CRM1": "Criminal",
  "CRM10": "Criminal",
  "CRM11": "Criminal",
  "CRM15": "Criminal",
  "CRM2": "Criminal",
  "CRM22": "Criminal",
  "CRM3": "Criminal",
  "CRM4": "Criminal",
  "CRM5": "Criminal",
  "CRM6": "Criminal",
  "CRM7": "Criminal",
  "CRM8": "Criminal",
  "CRM9": "Criminal",
  "CYBER 10": "Criminal",
  "DCCP01": "Criminal",
  "DCCP10": "Criminal",
  "DCPP 01": "Criminal",
  "DCPP 02": "Criminal",
  "DCPP 06": "Criminal",
  "DCPP 10": "Criminal",
  "DCPP 17": "Criminal",
  "DCPP02": "Criminal",
  "DIS 03": "Miscellaneous",
  "DUI 01": "Municipal",
  "DUI 02": "Municipal",
  "DUI 03": "Municipal",
  "DUI 06": "Municipal",
  "DUI 07": "Municipal",
  "DUI 08": "Municipal",
  "DUI 09": "Municipal",
  "DUI 10": "Municipal",
  "DUI 11": "Municipal",
  "DUI 14": "Municipal",
  "DUI 15": "Municipal",
  "DUI 16": "Municipal",
  "DUI 17": "Municipal",
  "DUI 18": "Municipal",
  "DUI 22": "Municipal",
  "DUI PCR 01": "Municipal",
  "DUI PCR 09": "Municipal",
  "DUI PCR 10": "Municipal",
  "DUI PCR 15": "Municipal",
  "DV12": "Criminal",
  "DV15": "Criminal",
  "DVD 07": "Criminal",
  "DVD 11": "Criminal",
  "DVD 14": "Criminal",
  "DVD 17": "Criminal",
  "DVD 9": "Criminal",
  "DVD1": "Criminal",
  "DVD10": "Criminal",
  "DVD15": "Criminal",
  "DVD2": "Criminal",
  "DVD3": "Criminal",
  "DVD4": "Criminal",
  "DVD5": "Criminal",
  "DVD6": "Criminal",
  "DVD8": "Criminal",
  "DVP 14": "Criminal",
  "DVP 15": "Criminal",
  "DVP 8": "Criminal",
  "DVP 9": "Criminal",
  "DVP1": "Criminal",
  "DVP10": "Criminal",
  "DVP11": "Criminal",
  "DVP2": "Criminal",
  "DVP3": "Criminal",
  "DVP4": "Criminal",
  "DVP5": "Criminal",
  "DVP6": "Criminal",
  "DVP7": "Criminal",
  "DYF1": "Criminal",
  "DYF11": "Criminal",
  "DYF2": "Criminal",
  "DYF3": "Criminal",
  "DYF4": "Criminal",
  "DYF5": "Criminal",
  "DYF6": "Criminal",
  "DYFS": "Criminal",
  "EMP 03": "Civil",
  "EMP 14": "Civil",
  "EST  03": "Miscellaneous",
  "EST 10": "Miscellaneous",
  "EST 12": "Miscellaneous",
  "EST 15": "Miscellaneous",
  "EST 18": "Miscellaneous",
  "EST 20": "Miscellaneous",
  "EST 21": "Miscellaneous",
  "EST LIT 03": "Civil",
  "EST LIT 08": "Civil",
  "EST LIT 12": "Civil",
  "EST LIT 14": "Civil",
  "EST LIT 18": "Civil",
  "EST LIT 20": "Civil",
  "EST03": "Miscellaneous",
  "EST1": "Miscellaneous",
  "EST12": "Miscellaneous",
  "EST14": "Miscellaneous",
  "EST2": "Miscellaneous",
  "EST20": "Miscellaneous",
  "EST4": "Miscellaneous",
  "EST6": "Miscellaneous",
  "EST8": "Miscellaneous",
  "ETH1": "Ethics",
  "ETH10": "Ethics",
  "ETH6": "Ethics",
  "ETH7": "Ethics",
  "EXP 10": "Expungements",
  "EXP 14": "Expungements",
  "EXP 15": "Expungements",
  "EXP 17": "Expungements",
  "EXP 18": "Expungements",
  "EXP1": "Expungements",
  "EXP11": "Expungements",
  "EXP2": "Expungements",
  "EXP3": "Expungements",
  "EXP4": "Expungements",
  "EXP5": "Expungements",
  "EXP6": "Expungements",
  "EXP7": "Expungements",
  "EXP8": "Expungements",
  "FAM1": "Family",
  "FAM2": "Family",
  "FAM3": "Family",
  "FAM4": "Family",
  "FAM5": "Family",
  "FAM6": "Family",
  "FHM20": "Family",
  "FMF 17": "Family",
  "FMF 18": "Family",
  "FMF1": "Family",
  "FMF10": "Family",
  "FMF11": "Family",
  "FMF12": "Family",
  "FMF14": "Family",
  "FMF17": "Family",
  "FMF18": "Family",
  "FMF2": "Family",
  "FMF3": "Family",
  "FMF4": "Family",
  "FMF5": "Family",
  "FMF6": "Family",
  "FMF8": "Family",
  "FMF9": "Family",
  "FMH 07": "Family",
  "FMH 14": "Family",
  "FMH 17": "Family",
  "FMH1": "Family",
  "FMH10": "Family",
  "FMH11": "Family",
  "FMH12": "Family",
  "FMH15": "Family",
  "FMH17": "Family",
  "FMH2": "Family",
  "FMH20": "Family",
  "FMH3": "Family",
  "FMH4": "Family",
  "FMH5": "Family",
  "FMH6": "Family",
  "FMH8": "Family",
  "FMH9": "Family",
  "GUARD 03": "Miscellaneous",
  "GUARD 08": "Miscellaneous",
  "GUARD 12": "Miscellaneous",
  "GUARD 14": "Miscellaneous",
  "IMF 14": "Immigration",
  "IMF 15": "Immigration",
  "IMF 8": "Immigration",
  "IMF1": "Immigration",
  "IMF10": "Immigration",
  "IMF11": "Immigration",
  "IMF16": "Immigration",
  "IMF17": "Immigration",
  "IMF2": "Immigration",
  "IMF3": "Immigration",
  "IMF4": "Immigration",
  "IMF5": "Immigration",
  "IMF6": "Immigration",
  "IMH1": "Immigration",
  "IMH2": "Immigration",
  "IMH3": "Immigration",
  "IMH4": "Immigration",
  "IMH5": "Immigration",
  "IMH6": "Immigration",
  "IMMFP 02": "Immigration",
  "IMMFP 11": "Immigration",
  "IMMFP 14": "Immigration",
  "IMMOC 01": "Immigration",
  "IMMOC 02": "Immigration",
  "IMMOC 03": "Immigration",
  "IMMOC 06": "Immigration",
  "IMMOC 07": "Immigration",
  "IMMOC 08": "Immigration",
  "IMMOC 09": "Immigration",
  "IMMOC 10": "Immigration",
  "IMMOC 11": "Immigration",
  "IMMOC 14": "Immigration",
  "IMMOC 15": "Immigration",
  "IMMOC 16": "Immigration",
  "INSAPP 10": "Appellate",
  "INSLIT14": "Civil",
  "JUV 14": "Criminal",
  "JUV 15": "Criminal",
  "JUV08": "Criminal",
  "JUV1": "Criminal",
  "JUV10": "Criminal",
  "JUV11": "Criminal",
  "JUV17": "Criminal",
  "JUV2": "Criminal",
  "JUV3": "Criminal",
  "JUV4": "Criminal",
  "JUV5": "Criminal",
  "JUV6": "Criminal",
  "JUV7": "Criminal",
  "JUV9": "Criminal",
  "L/T 18": "Miscellaneous",
  "L/T1": "Miscellaneous",
  "L/T10": "Miscellaneous",
  "L/T12": "Miscellaneous",
  "L/T14": "Miscellaneous",
  "L/T2": "Miscellaneous",
  "L/T20": "Miscellaneous",
  "L/T3": "Miscellaneous",
  "L/T4": "Miscellaneous",
  "L/T5": "Miscellaneous",
  "L/T6": "Miscellaneous",
  "L/T7": "Miscellaneous",
  "L/T8": "Miscellaneous",
  "LAND USE 03": "Civil",
  "LAND USE 08": "Civil",
  "LAND USE 12": "Civil",
  "LAND USE 19": "Civil",
  "LAND USE 20": "Civil",
  "LANDUSE14": "Civil",
  "LIT 14": "Civil",
  "LL 03": "Civil",
  "LL1": "Civil",
  "LL14": "Civil",
  "LLU1": "Civil",
  "MAL 7": "Personal Injury",
  "MAL14": "Personal Injury",
  "MAL2": "Personal Injury",
  "MAL4": "Personal Injury",
  "MALP03": "Personal Injury",
  "MEDIATION 08": "Miscellaneous",
  "MISC 01": "Miscellaneous",
  "MISC 02": "Miscellaneous",
  "MISC 03": "Miscellaneous",
  "MISC 12": "Miscellaneous",
  "MISC 15": "Miscellaneous",
  "MISC 20": "Miscellaneous",
  "MISC14": "Miscellaneous",
  "MISC17": "Miscellaneous",
  "MO10": "Criminal",
  "MO15": "Criminal",
  "MUN 15": "Municipal",
  "MUN 18": "Municipal",
  "MUN 20": "Municipal",
  "APPMUN GOVT LAW 0810": "Civil",
  "MUN GOVT LAW 10": "Civil",
  "MUN GOVT LAW 19": "Civil",
  "MUN LAW 1": "Civil",
  "MUN LAW 14": "Civil",
  "MUN1": "Municipal",
  "MUN10": "Municipal",
  "MUN11": "Municipal",
  "MUN14": "Municipal",
  "MUN16": "Municipal",
  "MUN17": "Municipal",
  "MUN2": "Municipal",
  "MUN22": "Municipal",
  "MUN3": "Municipal",
  "MUN4": "Municipal",
  "MUN5": "Municipal",
  "MUN6": "Municipal",
  "MUN7": "Municipal",
  "MUN8": "Municipal",
  "MUN9": "Municipal",
  "CONT7": "Personal Injury",
  "PI 10": "Personal Injury",
  "PI 14": "Personal Injury",
  "PI 8": "Personal Injury",
  "PI1": "Personal Injury",
  "PI15": "Personal Injury",
  "PI2": "Personal Injury",
  "PI3": "Personal Injury",
  "PI4": "Personal Injury",
  "PI5": "Personal Injury",
  "PI6": "Personal Injury",
  "PI7": "Personal Injury",
  "RE 09": "Miscellaneous",
  "RE 15": "Miscellaneous",
  "RE 20": "Miscellaneous",
  "RE1": "Miscellaneous",
  "RE10": "Miscellaneous",
  "RE12": "Miscellaneous",
  "RE14": "Miscellaneous",
  "RE17": "Miscellaneous",
  "RE18": "Miscellaneous",
  "RE2": "Miscellaneous",
  "RE20": "Miscellaneous",
  "RE21": "Miscellaneous",
  "RE3": "Miscellaneous",
  "RE4": "Miscellaneous",
  "RE5": "Miscellaneous",
  "RE6": "Miscellaneous",
  "RE7": "Miscellaneous",
  "RE8": "Miscellaneous",
  "SS 07": "Miscellaneous",
  "SS02": "Miscellaneous",
  "SS03": "Miscellaneous",
  "TAXAPP 03": "Civil",
  "TAXAPP14": "Civil",
  "W/C 10": "Workmans Comp",
  "W/C 11": "Workmans Comp",
  "W/C1": "Workmans Comp",
  "W/C15": "Workmans Comp",
  "W/C17": "Workmans Comp",
  "W/C2": "Workmans Comp",
  "W/C3": "Workmans Comp",
  "W/C4": "Workmans Comp",
  "W/C5": "Workmans Comp",
  "W/C6": "Workmans Comp",
  "W/C7": "Workmans Comp",
  "WC 11": "Workmans Comp",
  "WC 14": "Workmans Comp",
  "WC 7": "Workmans Comp",
  "WC18": "Workmans Comp",
  "WIL 15": "Miscellaneous",
  "WIL1": "Miscellaneous",
  "WIL10": "Miscellaneous",
  "WIL12": "Miscellaneous",
  "WIL2": "Miscellaneous",
  "WIL3": "Miscellaneous",
  "WIL4": "Miscellaneous",
  "WIL5": "Miscellaneous",
  "WIL6": "Miscellaneous",
  "WIL8": "Miscellaneous",
  "WILL": "Miscellaneous",
  "WILL 21": "Miscellaneous",
  "WILL14": "Miscellaneous",
  "WILL17": "Miscellaneous",
  "WILL18": "Miscellaneous",
}
