version: "3.8"

services:
  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    expose:
      - ${MONGODB_PORT}

volumes:
  node_modules_cache:
  redis-data:
  mongo-data: